### ISSUE TITLE
Analysis report part 1 feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [figalit/CS319-Group25#2]
Overall your report is fine. Please see attached for some improvements/corrections.
[25.analysis.1.pdf](https://github.com/figalit/CS319-Group25/files/545792/25.analysis.1.pdf)

**Comment by figalit** [comment]
[Analysis Report - Prefinal revision.pdf](https://github.com/figalit/CS319-Group25/files/549086/Analysis.Report.-.Prefinal.revision.pdf)

A revision of the highlighted parts is attached, currently working on completing the report for the final deadline of the proposal.

**Comment by ugurdogrusoz** [comment]
FYI, I will read and grade the Analysis report one more time but only when it's done.
